"""
================================================================================
BRICK: BRain dynamics Identification using Control and Koopman operator
================================================================================

Description:
    Full BRICK model integrating the encoder, control module, and Koopman
    operator into an end-to-end variational inference model.

    Forward pass (single session x of shape (T, N)):

        1. Encoder:      x -> g_0, mu_g0, logvar_g0
        2. Control:      x -> C, u_{1:T}, s_hat, mu_u, logvar_u
        3. Eigenspace:   assemble u_bar, run parallel scan -> g_bar_{1:T}
        4. Reconstruct:  x_hat = W_bar_x @ g_bar  where W_bar_x = W_x @ P
        5. Loss:         beta * L_cls + (1-beta) * L_ELBO

    The Koopman operator K = P @ diag(Lambda) @ P_inv is shared across all
    subjects. The control matrix C is per-subject-per-session, enabling
    individual-specific dynamics on top of shared brain dynamics.

    For the LiFUS dataset:
        - Run forward pass with mpre  -> get C_pre
        - Run forward pass with mpost -> get C_post
        - Delta_C = C_post - C_pre captures sonication effect per subject

    Training stabilization (not in original BRICK paper, added for N=19):
        - Separate KL annealing for g0 and u (see config.py)
        - Free bits on KL per dimension: gradient blocked below KL_U_FREE_BITS
        - Tighter prior on u_t: N(0, U_PRIOR_SIGMA^2) instead of N(0, I)
        - apply_free_bits=False for validation so true ELBO is evaluated

References:
    - Zhou et al. 2025 (BRICK paper)
    - Orvieto et al. 2023 (LRU paper)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from models.encoder import Encoder
from models.control import ControlModule
from models.koopman_utils import (
    init_koopman_params,
    compute_lambda,
    parallel_scan,
)

from config import (
    M, N_ROIS, H, NHEAD, NUM_LAYERS, BETA, NUM_CLASSES, EPSILON,
    KL_G0_FREE_BITS, KL_U_FREE_BITS, U_PRIOR_SIGMA, LAMBDA_NOISE, 
)


class BRICK(nn.Module):
    """
    Full BRICK model.

    Shared parameters (across all subjects):
        - nu_log, theta_log: eigenvalue parameters (-> Lambda)
        - P_inv: learned inverse eigenvector matrix
        - W_bar_x: complex reconstruction projection (N, M)
        - encoder weights
        - control module weights (except C which is per-subject)

    Per-subject-per-session parameters:
        - C: generated by control module from the input x

    Args:
        n_rois         (int):   Number of ROIs (N). Default from config.
        m              (int):   Latent dimension (M = N_ROIS * H). Default from config.
        h              (int):   Latent dims per ROI. Default from config.
        nhead          (int):   Attention heads. Default from config.
        num_layers     (int):   Transformer layers. Default from config.
        beta           (float): Loss balance: beta*L_cls + (1-beta)*L_ELBO.
        num_classes    (int):   Number of task states. Default from config.
        epsilon        (float): Prior variance for g_0 ~ N(0, epsilonI).
        use_control    (bool):  Ablation flag -- disable control module.
        use_ic         (bool):  Ablation flag -- disable initial condition (encoder).
        kl_u_free_bits (float): Free bits floor per KL dimension. Default from config.
    """

    def __init__(
        self,
        n_rois:         int   = N_ROIS,
        m:              int   = M,
        h:              int   = H,
        nhead:          int   = NHEAD,
        num_layers:     int   = NUM_LAYERS,
        beta:           float = BETA,
        num_classes:    int   = NUM_CLASSES,
        epsilon:        float = EPSILON,
        use_control:    bool  = True,
        use_ic:         bool  = True,
        kl_g0_free_bits: float = KL_G0_FREE_BITS,
        kl_u_free_bits: float = KL_U_FREE_BITS,
        lambda_noise:   float = LAMBDA_NOISE,
    ):
        assert m == n_rois * h, \
            f"Latent dimension mismatch: m={m} must equal n_rois*h={n_rois}*{h}={n_rois*h}. Check config.py."
        super().__init__()

        self.n_rois      = n_rois
        self.m           = m
        self.h           = h
        self.beta        = beta
        self.epsilon     = epsilon
        self.use_control = use_control
        self.use_ic      = use_ic
        self.free_bits_g0 = kl_g0_free_bits
        self.free_bits   = kl_u_free_bits
        self.lambda_noise = lambda_noise
        # --- Koopman operator parameters (shared across subjects) ---
        nu_log, theta_log, P_inv = init_koopman_params(m)
        self.nu_log    = nn.Parameter(nu_log)
        self.theta_log = nn.Parameter(theta_log)
        self.P_inv     = nn.Parameter(P_inv)

        # --- Reconstruction projection ---
        # W_bar_x = W_x @ P, learned directly as complex (N, M)
        self.W_bar_x = nn.Parameter(
            torch.complex(torch.randn(n_rois, m), torch.randn(n_rois, m)) / (m ** 0.5)
        )

        # --- Encoder: x -> g_0, mu_g0, logvar_g0 ---
        self.encoder = Encoder(n_rois=n_rois, h=h, nhead=nhead)

        # --- Control module: x -> C, u, s_hat, mu_u, logvar_u ---
        self.control = ControlModule(
            n_rois=n_rois,
            m=m,
            nhead=nhead,
            num_layers=num_layers,
            num_classes=num_classes,
        )

    def _assemble_u_bar(
        self,
        g_0:   torch.Tensor,
        C:     torch.Tensor,
        u:     torch.Tensor,
        P_inv: torch.Tensor,
    ) -> torch.Tensor:
        """
        Assemble u_bar sequence for parallel scan.

        u_bar[0]  = P_inv @ g_0        (initial condition in eigenspace)
        u_bar[t]  = P_inv @ C @ u_t    (control inputs in eigenspace, t=1,...,T)

        Args:
            g_0   (torch.Tensor): Initial latent state, shape (M,) real
            C     (torch.Tensor): Control matrix, shape (M, M) real
            u     (torch.Tensor): Control inputs, shape (T, M) real
            P_inv (torch.Tensor): Inverse eigenvector matrix, shape (M, M) complex

        Returns:
            torch.Tensor: u_bar of shape (T+1, M) complex
        """
        g_0_c = g_0.to(torch.complex64)
        C_c   = C.to(torch.complex64)
        u_c   = u.to(torch.complex64)

        u_bar_0 = (P_inv @ g_0_c).unsqueeze(0)  # (1, M)
        P_inv_C = P_inv @ C_c                    # (M, M)
        u_bar_t = (P_inv_C @ u_c.T).T           # (T, M)

        return torch.cat([u_bar_0, u_bar_t], dim=0)  # (T+1, M)

    def forward(
        self,
        x:              torch.Tensor,
        label:          torch.Tensor = None,
        kl_g0_weight:   float = 1.0,
        kl_u_weight:    float = 1.0,
        apply_free_bits: bool = True,
    ):
        """
        Full BRICK forward pass.

        Args:
            x               (torch.Tensor): BOLD timeseries, shape (T, N)
            label           (torch.Tensor): Task state label (0=pre, 1=post), shape ()
                                            Optional -- if None, cls loss is skipped.
            kl_g0_weight    (float):        KL annealing weight for g0. Default 1.0.
            kl_u_weight     (float):        KL annealing weight for u. Default 1.0.
            apply_free_bits (bool):         Apply free bits floor to KL terms.
                                            True during training, False during validation
                                            so the true ELBO is evaluated.

        Returns:
            dict with keys:
                x_recon      (torch.Tensor): Reconstructed BOLD, shape (T, N)
                g_trajectory (torch.Tensor): Latent trajectory, shape (T, M) complex
                C            (torch.Tensor): Control matrix, shape (M, M)
                s_hat        (torch.Tensor): Task state logits, shape (num_classes,)
                losses       (dict): All loss components
        """
        T, _ = x.shape
        Lambda = compute_lambda(self.nu_log, self.theta_log)
        P_inv  = self.P_inv

        # ------------------------------------------------------------------ #
        # 1. Initial condition (encoder)
        # ------------------------------------------------------------------ #
        if self.use_ic:
            g_0, mu_g0, logvar_g0 = self.encoder(x)
        else:
            # Ablation: no encoder, no learned initial condition, no KL_g0
            g_0       = torch.zeros(self.m, device=x.device)
            mu_g0     = g_0
            logvar_g0 = torch.zeros(self.m, device=x.device)

        # ------------------------------------------------------------------ #
        # 2. Control module
        # ------------------------------------------------------------------ #
        if self.use_control:
            C, u, s_hat, mu_u, logvar_u = self.control(x)
        else:
            # Ablation: no control module, no KL_u
            C        = torch.zeros(self.m, self.m, device=x.device)
            u        = torch.zeros(T, self.m, device=x.device)
            s_hat    = torch.zeros(self.control.num_classes, device=x.device)
            mu_u     = torch.zeros(T, self.m, device=x.device)
            logvar_u = torch.zeros(T, self.m, device=x.device)

        # ------------------------------------------------------------------ #
        # 3. Assemble u_bar and run parallel scan in eigenspace
        # ------------------------------------------------------------------ #
        u_bar   = self._assemble_u_bar(g_0, C, u, P_inv)  # (T+1, M) complex
        g_bar   = parallel_scan(Lambda, u_bar)              # (T+1, M) complex
        g_bar   = g_bar[1:]                                 # drop slot 0 (g_0 entry)

        # x_hat = real(W_bar_x @ g_bar)
        x_recon = (self.W_bar_x @ g_bar.T).T.real          # (T, N) real

        # ------------------------------------------------------------------ #
        # 4. Compute losses
        # ------------------------------------------------------------------ #
        losses = self._compute_losses(
            x=x,
            x_recon=x_recon,
            mu_g0=mu_g0,
            logvar_g0=logvar_g0,
            mu_u=mu_u,
            logvar_u=logvar_u,
            s_hat=s_hat,
            label=label,
            kl_g0_weight=kl_g0_weight,
            kl_u_weight=kl_u_weight,
            apply_free_bits=apply_free_bits,
        )

        return {
            "x_recon":      x_recon,
            "g_trajectory": g_bar,
            "C":            C,
            "s_hat":        s_hat,
            "losses":       losses,
        }

    def _compute_losses(
        self,
        x:               torch.Tensor,
        x_recon:         torch.Tensor,
        mu_g0:           torch.Tensor,
        logvar_g0:       torch.Tensor,
        mu_u:            torch.Tensor,
        logvar_u:        torch.Tensor,
        s_hat:           torch.Tensor,
        label:           torch.Tensor = None,
        kl_g0_weight:    float = 1.0,
        kl_u_weight:     float = 1.0,
        apply_free_bits: bool  = True,
    ) -> dict:
        """
        Normalized-ELBO losses on a single global per-observation scale.

        Convention: the whole ELBO (recon + KL terms) is divided by T*N so
        all components are on the same scale as F.mse_loss (mean over T*N).

        KL_g0 and KL_u have separate annealing weights so they can be ramped
        independently — KL_u is held at 0 for KL_U_DELAY_EPOCHS epochs so
        reconstruction can stabilize before the control pathway is regularized.

        Free bits (apply_free_bits=True during training only):
            Applied per-dimension BEFORE summing. Below the floor the term is
            constant -> zero gradient, preventing collapse without suppressing
            the pathway when it is encoding something useful.
            apply_free_bits=False during validation so the true ELBO is
            evaluated and early stopping is not biased by the floor constant.

        Tighter prior on u_t: N(0, U_PRIOR_SIGMA^2) instead of N(0, I).
            Raises the minimum achievable KL at initialization, preventing
            immediate collapse before any learning occurs.

        Args:
            x               (torch.Tensor): Original BOLD, shape (T, N)
            x_recon         (torch.Tensor): Reconstructed BOLD, shape (T, N)
            mu_g0           (torch.Tensor): Posterior mean of g_0, shape (M,)
            logvar_g0       (torch.Tensor): Posterior log variance of g_0, shape (M,)
            mu_u            (torch.Tensor): Posterior mean of u, shape (T, M)
            logvar_u        (torch.Tensor): Posterior log variance of u, shape (T, M)
            s_hat           (torch.Tensor): Task state logits, shape (num_classes,)
            label           (torch.Tensor): True task state label, shape ()
            kl_g0_weight    (float):        Annealing weight for KL_g0, in [0, 1]
            kl_u_weight     (float):        Annealing weight for KL_u, in [0, 1]
            apply_free_bits (bool):         Apply per-dim free bits floor to KL terms.

        Returns:
            dict: loss_total, loss_recon, loss_kl_g0, loss_kl_u, loss_cls
        """
        T, N = x.shape

        # --- Reconstruction ---
        recon_sq = (x - x_recon).pow(2).sum() / (T*N)
        loss_recon = 0.5 / self.lambda_noise * recon_sq

        # --- KL(g_0): KL(N(mu, sigma^2) || N(0, epsilon*I)) ---
        if self.use_ic:
            var_g0        = torch.exp(logvar_g0)
            kl_g0_per_dim = 0.5 * (
                var_g0 / self.epsilon
                + mu_g0 ** 2 / self.epsilon
                - 1.0
                - torch.log(var_g0 / self.epsilon)
            )
            if apply_free_bits:
                kl_g0_per_dim = torch.clamp(kl_g0_per_dim, min=self.free_bits_g0)
            loss_kl_g0 = kl_g0_per_dim.sum() / M
        else:
            loss_kl_g0 = torch.zeros((), device=x.device)

        # --- KL(u): KL(N(mu_u, sigma_u^2) || N(0, U_PRIOR_SIGMA^2)) ---
        # Tighter prior raises minimum achievable KL at init, preventing
        # immediate collapse before any learning occurs.
        if self.use_control:
            var_u        = torch.exp(logvar_u)
            sigma_p2     = U_PRIOR_SIGMA ** 2
            kl_u_per_dim = 0.5 * (
                var_u / sigma_p2
                + mu_u ** 2 / sigma_p2
                - 1.0
                - torch.log(var_u / sigma_p2)
            )
            if apply_free_bits:
                kl_u_per_dim = torch.clamp(kl_u_per_dim, min=self.free_bits)
            loss_kl_u = kl_u_per_dim.sum() / (T*M)  #Normalize to T*N since u is a sequence per observation)
        else:
            loss_kl_u = torch.zeros((), device=x.device)

        # --- ELBO with separate annealing weights ---
        loss_elbo = loss_recon + kl_g0_weight * loss_kl_g0 + kl_u_weight * loss_kl_u

        # --- Classification loss ---
        if label is not None and self.use_control:
            loss_cls = F.cross_entropy(
                s_hat.unsqueeze(0), label.unsqueeze(0).long()
            )
        else:
            loss_cls = torch.tensor(0.0, device=x.device)

        # --- Total loss ---
        loss_total = self.beta * loss_cls + (1.0 - self.beta) * loss_elbo

        return {
            "loss_total": loss_total,
            "loss_recon": loss_recon,
            "loss_kl_g0": loss_kl_g0,
            "loss_kl_u":  loss_kl_u,
            "loss_cls":   loss_cls,
        }