"""
================================================================================
BRICK: BRain dynamics Identification using Control and Koopman operator
================================================================================

Description:
    Full BRICK model integrating the encoder, control module, and Koopman
    operator into an end-to-end variational inference model.

    Forward pass (single session x of shape (T, N)):

        1. Encoder:      x → g_0, mu_g0, logvar_g0
        2. Control:      x → C, u_{1:T}, s_hat, mu_u, logvar_u
        3. Eigenspace:   assemble u_bar, run parallel scan → ḡ_{1:T}
        4. Reconstruct:  x̂ = W̄_x @ ḡ  where W̄_x = W_x @ P
        5. Loss:         β * L_cls + (1-β) * L_ELBO

    The Koopman operator K = P @ diag(Lambda) @ P_inv is shared across all
    subjects. The control matrix C is per-subject-per-session, enabling
    individual-specific dynamics on top of shared brain dynamics.

    For the LiFUS dataset:
        - Run forward pass with mpre → get C_pre
        - Run forward pass with mpost → get C_post
        - ΔC = C_post - C_pre captures sonication effect per subject

References:
    - Zhou et al. 2025 (BRICK paper)
    - Orvieto et al. 2023 (LRU paper)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from models.encoder import Encoder
from models.control import ControlModule
from models.koopman_utils import (
    init_koopman_params,
    compute_lambda,
    parallel_scan,
)

from config import M, N_ROIS, H, NHEAD, NUM_LAYERS, BETA, NUM_CLASSES, EPSILON


class BRICK(nn.Module):
    """
    Full BRICK model.

    Shared parameters (across all subjects):
        - nu_log, theta_log: eigenvalue parameters (→ Lambda)
        - P: eigenvector matrix
        - W_x: reconstruction projection (N, M)
        - encoder weights
        - control module weights (except C which is per-subject)

    Per-subject-per-session parameters:
        - C: generated by control module from the input x

    Args:
        n_rois      (int): Number of ROIs (N). Default from config.
        m           (int): Latent dimension (M). Default from config.
        beta        (float): Loss balance parameter β. Default from config.
        num_classes (int): Number of task states. Default from config.
        epsilon     (float): Prior variance for g_0 ~ N(0, εI). Default from config.
        use_control (bool): Ablation flag — disable control module.
        use_ic      (bool): Ablation flag — disable initial condition (encoder).
    """

    def __init__(
        self,
        n_rois:       int   = N_ROIS,
        m:            int   = M,
        h:            int   = H,
        nhead:        int   = NHEAD,
        num_layers:   int   = NUM_LAYERS,
        beta:         float = BETA,
        num_classes:  int   = NUM_CLASSES,
        epsilon:      float = EPSILON,
        use_control:  bool  = True,
        use_ic:       bool  = True,
    ):   
        super().__init__()

        self.n_rois      = n_rois
        self.m           = m
        self.h           = h
        self.beta        = beta
        self.epsilon     = epsilon
        self.use_control = use_control
        self.use_ic      = use_ic

        # --- Koopman operator parameters (shared across subjects) ---
        nu_log, theta_log, P_inv = init_koopman_params(m)
        self.nu_log    = nn.Parameter(nu_log)
        self.theta_log = nn.Parameter(theta_log)
        self.P_inv     = nn.Parameter(P_inv)

        # --- Reconstruction projection W_x: g → x ---
        # Output projection W̄_x = W_x P, learned directly as complex (N, M)
        self.W_bar_x = nn.Parameter(
            torch.complex(torch.randn(n_rois, m), torch.randn(n_rois, m)) / (m ** 0.5)
        )

        # --- Encoder: x → g_0, mu_g0, logvar_g0 ---
        self.encoder = Encoder(n_rois=n_rois, h=h)

        # --- Control module: x → C, u, s_hat, mu_u, logvar_u ---
        self.control = ControlModule(
            n_rois=n_rois,
            m=m,
            nhead=nhead,
            num_layers=num_layers,
            num_classes=num_classes,
        )

    def _get_koopman(self):
        """Compute Lambda and P_inv from current parameters."""
        Lambda = compute_lambda(self.nu_log, self.theta_log)  # (M,) complex                 
        return Lambda

    def _assemble_u_bar(
        self,
        g_0:   torch.Tensor,
        C:     torch.Tensor,
        u:     torch.Tensor,
        P_inv: torch.Tensor,
    ) -> torch.Tensor:
        """
        Assemble u_bar sequence for parallel scan.

        u_bar[0]  = P_inv @ g_0        (initial condition in eigenspace)
        u_bar[t]  = P_inv @ C @ u_t    (control inputs in eigenspace, t=1,...,T)

        Args:
            g_0   (torch.Tensor): Initial latent state, shape (M,) real
            C     (torch.Tensor): Control matrix, shape (M, M) real
            u     (torch.Tensor): Control inputs, shape (T, M) real
            P_inv (torch.Tensor): Inverse eigenvector matrix, shape (M, M) complex

        Returns:
            torch.Tensor: u_bar of shape (T+1, M) complex
        """

        # Cast to complex for eigenspace operations
        g_0_c = g_0.to(torch.complex64)
        C_c   = C.to(torch.complex64)
        u_c   = u.to(torch.complex64)

        # u_bar[0] = P_inv @ g_0
        u_bar_0 = (P_inv @ g_0_c).unsqueeze(0)  # (1, M)

        # u_bar[t] = P_inv @ (C @ u_t) = (P_inv @ C) @ u_t
        P_inv_C = P_inv @ C_c                    # (M, M)
        u_bar_t = (P_inv_C @ u_c.T).T           # (T, M)

        return torch.cat([u_bar_0, u_bar_t], dim=0)  # (T+1, M)

    def forward(self, x: torch.Tensor, label: torch.Tensor = None):
        """
        Full BRICK forward pass.

        Args:
            x     (torch.Tensor): BOLD timeseries, shape (T, N)
            label (torch.Tensor): Task state label (0=pre, 1=post), shape ()
                                  Optional — if None, classification loss is skipped.

        Returns:
            dict with keys:
                x_recon      (torch.Tensor): Reconstructed BOLD, shape (T, N)
                g_trajectory (torch.Tensor): Latent trajectory, shape (T, M) real
                C            (torch.Tensor): Control matrix, shape (M, M)
                s_hat        (torch.Tensor): Task state logits, shape (num_classes,)
                losses       (dict): All loss components
        """
        T, _ = x.shape
        Lambda = self._get_koopman()
        P_inv  = self.P_inv

        # ------------------------------------------------------------------ #
        # 1. Initial condition (encoder)
        # ------------------------------------------------------------------ #
        if self.use_ic:
            g_0, mu_g0, logvar_g0 = self.encoder(x)
        else:                                                   #for ablation study
            g_0      = torch.zeros(self.m, device=x.device)     #no encoder, no learned inital condition
            mu_g0    = g_0                                      #no KL loss (divergence pentalty in ELBO) for G_0
            logvar_g0 = torch.zeros(self.m, device=x.device)

        # ------------------------------------------------------------------ #
        # 2. Control module
        # ------------------------------------------------------------------ #
        if self.use_control:
            C, u, s_hat, mu_u, logvar_u = self.control(x)
        else:                                                   #for ablation study
            C        = torch.zeros(self.m, self.m, device=x.device)
            u        = torch.zeros(T, self.m, device=x.device)
            s_hat    = torch.zeros(self.control.num_classes, device=x.device)
            mu_u     = torch.zeros(T, self.m, device=x.device)
            logvar_u = torch.zeros(T, self.m, device=x.device)

        # ------------------------------------------------------------------ #
        # 3. Assemble u_bar and run parallel scan in eigenspace
        # ------------------------------------------------------------------ #
        u_bar  = self._assemble_u_bar(g_0, C, u, P_inv)  # (T+1, M) complex
        g_bar  = parallel_scan(Lambda, u_bar)              # (T+1, M) complex
        g_bar  = g_bar[1:]                                 # drop slot 0 (g_0-only)

        # x̂ = real(W̄_x ḡ) — paper's reformulation, applied directly in eigenspace
        x_recon = (self.W_bar_x @ g_bar.T).T.real          # (T, N) real

        # ------------------------------------------------------------------ #
        # 4. Compute losses
        # ------------------------------------------------------------------ #
        losses = self._compute_losses(
            x=x,
            x_recon=x_recon,
            mu_g0=mu_g0,
            logvar_g0=logvar_g0,
            mu_u=mu_u,
            logvar_u=logvar_u,
            s_hat=s_hat,
            label=label,
        )

        return {
            "x_recon":      x_recon,
            "g_trajectory": g_bar,
            "C":            C,
            "s_hat":        s_hat,
            "losses":       losses,
        }

    def _compute_losses(
        self,
        x:          torch.Tensor,
        x_recon:    torch.Tensor,
        mu_g0:      torch.Tensor,
        logvar_g0:  torch.Tensor,
        mu_u:       torch.Tensor,
        logvar_u:   torch.Tensor,
        s_hat:      torch.Tensor,
        label:      torch.Tensor = None,
    ) -> dict:
        """
        Compute all loss components.

        L_total = β * L_cls + (1-β) * L_ELBO
        L_ELBO  = L_recon + L_KL
        L_KL    = KL(q(g_0|x) || p(g_0)) + KL(q(u|x) || p(u))

        Args:
            x          (torch.Tensor): Original BOLD, shape (T, N)
            x_recon    (torch.Tensor): Reconstructed BOLD, shape (T, N)
            mu_g0      (torch.Tensor): Posterior mean of g_0, shape (M,)
            logvar_g0  (torch.Tensor): Posterior log variance of g_0, shape (M,)
            mu_u       (torch.Tensor): Posterior mean of u, shape (T, M)
            logvar_u   (torch.Tensor): Posterior log variance of u, shape (T, M)
            s_hat      (torch.Tensor): Task state logits, shape (num_classes,)
            label      (torch.Tensor): True task state label, shape ()

        Returns:
            dict with scalar losses: loss_total, loss_recon, loss_kl_g0,
                                     loss_kl_u, loss_cls
        """
        # Reconstruction loss (Gaussian likelihood)
        loss_recon = F.mse_loss(x_recon, x)     # (T, N)

        # KL for g_0: KL(N(mu, sigma^2) || N(0, epsilon*I))
        var_g0     = torch.exp(logvar_g0)
        loss_kl_g0 = 0.5 * (
            var_g0 / self.epsilon
            + mu_g0 ** 2 / self.epsilon
            - 1.0
            - torch.log(var_g0 / self.epsilon)
        ).sum()

        # KL for u: KL(N(mu_u, sigma_u^2) || N(0, I))
        var_u      = torch.exp(logvar_u)
        loss_kl_u  = 0.5 * (var_u + mu_u ** 2 - 1.0 - logvar_u).sum()

        # ELBO
        loss_elbo = loss_recon + loss_kl_g0 + loss_kl_u

        # Classification loss
        if label is not None and self.use_control:
            loss_cls = F.cross_entropy(
                s_hat.unsqueeze(0), label.unsqueeze(0).long()
            )
        else:
            loss_cls = torch.tensor(0.0, device=x.device)

        # Total loss
        loss_total = self.beta * loss_cls + (1.0 - self.beta) * loss_elbo

        return {
            "loss_total": loss_total,
            "loss_recon": loss_recon,
            "loss_kl_g0": loss_kl_g0,
            "loss_kl_u":  loss_kl_u,
            "loss_cls":   loss_cls,
        }